### PR TITLE
Update Mongoose and Mongodb versions

### PR DESCRIPTION
**Pull request by joaoluizn**
Updated versions to recent stable patches to avoid a connection problem that wasn't establishing a connection to the db.
After the version update, the project seems to be running and connecting.

### CODE REVIEW

**Comment by joaoluizn** [comment]
Please update the Glitch project to save other people too.

**Comment by joaoluizn** [comment]
I spent some time having problems with mongo connection and it was weird because I've done some FCC challenges before using the same DB and configs. 

When I figured out, it was the versions that were affecting the connection, so for some reason, newer versions are free from this bug.

If validation is needed, just try to connect using this current repository version and log the connection status, try to change the listed versions and it will just connect fine.

**Comment by asianvader** [comment]
I agree with these changes. I've tested the above changes and it works.

Can we please have this merged?

**Comment by joaoluizn** [comment]
@JosephLivengood Could you review this? Thanks

**Comment by scissorsneedfoodtoo** [comment]
Hi @joaoluizn, thanks for your patience.

Would you be able to update both mongodb and mongoose to the latest versions? Also, would you be able to solve the merge conflict in package.json?

**Comment by joaoluizn** [comment]
Sure @scissorsneedfoodtoo, 

Should the node version be updated too, or just these?

And these will be updates to the latest possible with node 4.4.5?

Thanks.

**Comment by scissorsneedfoodtoo** [comment]
Good point @joaoluizn. 

This PR updated some of the dependencies and the Node version we're using: https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/15

The newest versions of Mongo and Mongoose should work with Node 10.

**Comment by joaoluizn** [comment]
Updated the package versions to latest and also the node version as we discussed.
Acidentally I've pushed a wrong package-lock, and then corrected it with commit 3122257.

- [x] Conflicts Solved

- [x] Tested on my personal glitch submission

Also, noticed that the latest version from mongoose, requires the mongodb. With this, I am wondering if the mongodb isn't required anymore as an explicit requirement. What do you think, @scissorsneedfoodtoo?

I think its now ready for review and test.

Thanks!

**Comment by scissorsneedfoodtoo** [comment]
Hi @joaoluizn, thanks for your patience and for updating this PR.

I also tested this on my old solution to this project and everything LGTM.

It's true, Mongoose doesn't require MongoDB to also be installed. But I think it doesn't hurt in this case -- people going through the project can choose whether to use Mongoose or the Node MongoDB driver directly.

Thanks again for taking the time to update this :+1: :+1:

**Pull request merged**
