### PR TITLE
Fix: App API and freeCodeCamp URLs

### PR DESCRIPTION
**Pull request by huyenltnguyen**
This PR:
- Changes `thread-paper.hyperdev.space` to `thread-paper.glitch.me`
- Changes `forum.freecodecamp.com` to `freecodecamp.org/forum/`
- Changes `freecodecamp.com` to `freecodecamp.org`
- Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17550

### CODE REVIEW

**Comment by momozor** [comment]
Hi. It is already March in 2019. I wonder when this PR is going to be merged? This PR should fix the freeCodeCamp/freeCodeCamp#17550 issue. @RandellDawson

**Comment by huyenltnguyen** [comment]
Hah! @momozor Thanks a lot for reminding me that I had an open PR here 😆 

@RandellDawson @raisedadead Thanks for reviewing and the merge! 👍

**Comment by KaustubhD** [comment]
I see the PR has been merged, but the glitch project still has the incorrect URLs

**Comment by momozor** [comment]
@KaustubhD I can confirm this.

**Comment by raisedadead** [comment]
We have updated the project. Thanks for your patience.

**Pull request merged**
