### PR TITLE
chore: clarify readme

### PR DESCRIPTION
**Pull request by nhcarrigan**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/44192

This PR adds clarification to the readme for where to find the instructions to complete the project.

When we are happy with the verbiage, I will do the same for our other boilerplate repos.

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
I am happy to go with this. However, we specifically simplified the READMEs, because of the added maintenance issues.

So, in my opinion, I would simplify this to nothing more than:

```markdown
# URL Shortener Microservice
```

**Comment by nhcarrigan** [comment]
That is what we already had. The discussion in the linked issue explains the need for some additional verbiage.

**Comment by ShaunSHamilton** [comment]
I am suggesting we not even have the link in the title.

---

I do not understand the issue, because Campers come from `/learn`, and then look for user stories, and are redirected back to `/learn` to find them?

The only 'confusion' with this project is that we do not have/require unit tests to be written.

**Comment by nhcarrigan** [comment]
I think the link is helpful, especially if a camper is returning to the project after taking a break.

**Pull request merged**
